# Generated by Django 4.1.7 on 2023-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(null=True, to='myapp.genres'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
